### ISSUE TITLE
Upgrade bash

### ISSUE THREAD

**Issue by docwhat** [msysgit/msysgit#193]
Please consider upgrading bash to the latest 3.2.x version at least.

Version 3.1.0 has some bugs involving the `local` and arrays that are fixed in 3.2-release.

There are lots of other bugfixes in 3.2 as well, so I hope it would be an overall positive.

**Comment by ingydotnet** [comment]
I have 2 fairly popular git commands:

* https://github.com/ingydotnet/git-subrepo
* https://github.com/ingydotnet/git-hub

that depend on Bash 3.2. Both are fairly large bash codebases.

I dep on 3.2 because that's what OSX seems pinned to (and never changing).

The main difference between 3.1 and 3.2 is regex support. I use Bash regexes quite a bit in my code.

Bugs have been opened in both projects to get them working in msysgit:

* https://github.com/ingydotnet/git-hub/issues/161
* https://github.com/ingydotnet/git-subrepo/issues/38

I might take this on at some point, or hopefully someone else will do it in the meantime. Leaving this comment for full-circle posterity.

**Comment by dscho** [comment]
Please note that [Git for Windows 2.x](https://git-for-windows.github.io) supersedes now-deprecated msysGit-based Git for Windows 1.x, and comes with Bash 4.3.
