### ISSUE TITLE
Let the installer detect certain editors and suggest them as default editors

### ISSUE THREAD

**Issue by dscho** [msysgit/msysgit#218]
Most Windows users are really uncomfortable with `vi`. There are many alternatives, and we should detect them when they are installed. Maybe even offer to download and install [Notepad++](http://www.notepad-plus-plus.org/) (and make it the default editor).

Unless @ctrueden beats me to it, I will take care of this. Eventually.

**Comment by Utumno** [comment]
Just detect notepad++ and accept patches for other common editors.
The editor makes a huge difference - think rebase. Notepad++ if present is perfect for the job. Detect from registry.

**Comment by dscho** [comment]
@Utumno we kinda reached that conclusion already, thank you for confirming, though. The issue is people who actually work on this instead of just chatting about it ;-)

**Comment by uNiversaI** [comment]
> Just detect notepad++ and accept patches for other common editors.
> The editor makes a huge difference - think rebase. Notepad++ if present is perfect for the job. Detect from registry.

:+1: 

> @Utumno we kinda reached that conclusion already, thank you for confirming, though. The issue is people who actually work on this instead of just chatting about it ;-)

:+1: :+1:

**Comment by uNiversaI** [comment]
@dscho 

because of https://github.com/git-for-windows/git/issues/278 and because this is now a year old and I cant really fix that properly here and while a qualified volunteer doesn't come forth with a proper solution I opened https://github.com/progit/progit/issues/942 in order to document the workaround in meanwhile.

This I can do so pending feedback and reply to https://github.com/progit/progit/issues/942 I will proceed on that front. If you have anything to add to these docs please reply there, if you have something to point out in order to resolve this in core, please point to right source fies and Ill have a looksee to determine if I can hack the solution in.

**Comment by dscho** [comment]
Closed in favor of https://github.com/git-for-windows/git/issues/291.
