### ISSUE TITLE
Kapersky reports that the GIT-1.9.4-PREVIEW10140929.EXE contains PDM.Worm.P2P.generic

### ISSUE THREAD

**Issue by antoncl** [msysgit/msysgit#259]
Can you confirm whether this is a false positive?

**Comment by crossique** [comment]
GIT-1.9.5-PREVIEW20150319.EXE is also reported by Karspersky to contain PDM.Worm.P2P.generic !!!

**Comment by dolmen** [comment]
@crossique: Please read all the comments above to give a useful report.

**Comment by dscho** [comment]
My experience with roughly a dozen reports about viruses in our installer is that we have a 100% clean record. No viruses, no trojans, no nothing. Every single time it turned out that our software was uninfected and the anti-virus software was wrong. In one case, it took the company some 2.5 years to figure that out, but in the end they admitted that it was a false positive.

Now, in all of those cases only a couple of the Git for Windows versions were being questioned, while others were declared safe that had been produced with exactly the same toolchain, on exactly the same computer, in exactly the same way. The same goes for 1.9.5 and the upcoming 2.x releases. There was a change how 2.x releases are made, relative to 1.x but in both cases subsequent Git for Windows versions have been labeled harmless and harmful, respectively, by some anti-virus software. This, of course, makes no sense: having used the exact same scripts, with the exact same InnoSetup version or `.7z` SFX component, it should be an all-or-nothing effect: either they are all infected, or none of them.

Another important data point: in every single incident report, it was impossible for me to get ahold of anybody in the anti-virus software company to work through the issue. In every single case the problem was that I am not a customer of theirs, so they refused to give me customer support. Naturally, I agree: not being a customer of theirs, I have no right to take their time.

As a consequence my reaction to reports that some anti-virus or other thinks Git for Windows is virus-ridden, I react calmer and calmer every time and simply ask the customer of the anti-virus software company to contact them first, and to come back only when they have proof that there is actually a virus in our software (in which case I will be very glad to get rid of the virus if they company helps me with it), or, much more likely by our track record, when they have proof that it was a false positive.
