### ISSUE TITLE
Github Bash for Windows crashes using the CVE-2014-7186 PoC

### ISSUE THREAD

**Issue by shipcod3** [msysgit/msysgit#272]
By inputting the code below you crash the Git Shell:

true <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF <<EOF' || echo 'AAAAAA'

As a side note, I'm using the Github for Windows version 2.6.6.2.

**Comment by dscho** [comment]
What *Git for Windows* and Bash version is this? (`git --version; bash --version`). It may be that GitHub for Windows does not quite ship with our most recent release yet? Maybe @shiftkey knows more (picking this nick from the most recent commits in https://github.com/github/msysgit/commits/devel)?

**Comment by shipcod3** [comment]
Here is the Git and Bash Version:

git version 1.9.5.github.0
GNU bash, version 3.1.20(4)-release (i686-pc-msys)

**Comment by dscho** [comment]
@shipcod3 ouch, that *is* the newest release. Hopefully you have a little time to help us out here... Do you know whether there is a Bash version that fixed this?

**Comment by shipcod3** [comment]
As what I know from the resolution of shellshock for RHEL, bash-4.1.2-15.el6_5.2 should fix this kind of issue.

**Comment by nak5124** [comment]
CVE-2014-7186 and CVE-2014-7187 were fixed at 3.1.21
here is the patch http://ftp.gnu.org/gnu/bash/bash-3.1-patches/bash31-021

**Comment by shiftkey** [comment]
@nak5124 :heart: for the new patch

**Comment by shiftkey** [comment]
@dscho yeah, we've working from the latest tip of msysgit (I tagged the version different because the upstream tag wasn't pushed at the time which caused a custom tag).

**Comment by dscho** [comment]
> the upstream tag wasn't pushed at the time

Ah, yes, of course, for security reasons (we fixed a critical bug and I did not want people who think like yours truly to analyze the patch to play pranks on their friends). However, GitHub had full access to the changes I made (my work was gracefully sponsored by GitHub), Peff contacted the GitHub for Windows team...

**Comment by shiftkey** [comment]
@dscho :thumbsup: just a logistical blip which hit us at build time

**Comment by dscho** [comment]
@nak5124 how about giving it a try?

Recompiling the Bash is pretty easy (unless you are sitting in a scientific symposium where the ports are blocked that you need to access your Windows VM :frowning:):

1. install the *Git for Windows* development environment (see the bottom part of https://msysgit.github.io/)
2. install a shortcut (by following the hint about `add-shortcut.tcl`
3. *close* the msysGit window
4. use *Git for Windows* (i.e. **not** msysGit) to check out the `msys` branch in `C:\msysgit` (or wherever you installed the development environment)
5. restart *msysGit* using the previously installed shortcut
6. add the patch, imitating 22d376a7cca337b97d3b332587992e4f8e1e6ecd
7. rebuild the bash using `/src/rt/release.sh bash`
8. *close* the msysGit window and use *Git for Windows* to switch back to the `master` branch
9. cherry-pick the new Bash (`git cherry-pick msys`)
10. Test
11. Open a PR

(You need to close the *msysGit* window so that the `.dll`/`.exe` files can be replaced; they are in use while *msysGit* is running.)

**Comment by sschuberth** [comment]
Just FYI, the new [Git SDK](https://github.com/git-for-windows/sdk/) ships with Bash 3.1.23 and I just verified that it's not affected by this bug.

**Comment by t-b** [comment]
https://github.com/msysgit/msysgit/pull/273 should do the trick.

**Comment by dscho** [comment]
@t-b you rock. @nak5124 @shipcod3 y'all owe @t-b more than just a couple of thankyous.

I cherry-picked the new Bash here: b1500d9

**Comment by dscho** [comment]
@t-b @sschuberth together with the backported rebase fix, I think I could release a new 1.9.5.msysgit.1 by the end of this week; do you agree?

@shiftkey I'll notify you via mail when the new release is available, okay? Or is there a better way to notify the GitHub for Windows team than to write a private mail to you?

**Comment by dscho** [comment]
Oh, and for the record, I tested the invocation mentioned by @shipcod3 (thanks so much for this!) and it is indeed fixed by the patches Bash.

**Comment by shiftkey** [comment]
@dscho if you publish a release on this repo, I'll see it :metal:

**Comment by dscho** [comment]
> @dscho if you publish a release on this repo, I'll see it :metal:

Of course! GitHub rocks.

**Comment by sschuberth** [comment]
> I think I could release a new 1.9.5.msysgit.1 by the end of this week; do you agree?

Sure, go for it @dscho, and thanks in advance! :-)

**Comment by shipcod3** [comment]
Thanks guys \m/ especially @t-b
