### ISSUE TITLE
Checkout on Windows is not case sensitive, but push is case sensitive.  

### ISSUE THREAD

**Issue by Reza-sh** [msysgit/msysgit#281]
This is on Windows 8.1 and with version 1.9.5. I am also using powershell to run git commands.

Assume you have a branch called MyBranch. If you accidentally type "git checkout myBranch" instead of MyBranch. Git checks out the branch for you. If you don't notice your error and push the branch to the origin, it creates a new branch on the server called myBranch. This can cause lots of confusion and also leads to some bad ref error for other team members when they try to push even using the correct branch.

I think git checkout on windows should to be case sensitive, and show error in the above example like Linux does. This avoids lots of problem and keeps things consistence.

**Comment by sschuberth** [comment]
Some background information: Git manages branches as file names on the file system, so this basically is caused by a case-insensitive filesystem on the client (Windows) vs. a case-sensitive filesystem on the server (Linux).

However you can configure your Git with `core.ignorecase=false`, which should solve your issue. For more details see the [help for git config](http://git-scm.com/docs/git-config.html).

**Comment by tboegi** [comment]
I don't think that setting core.ignorecase=false will help here, because the underlying file system will
treat MyBranch and myBranch the same, and Git can not do much about it.
This may help:
git pack-refs --all
