### ISSUE TITLE
SSH-Agent.exe causing port listening storm?

### ISSUE THREAD

**Issue by PlNG** [msysgit/msysgit#291]
Can anyone else confirm that SSH-Agent.exe is causing a port listening storm after running for a while (an hour to a day+)?

I discovered this when I started lagging heavily and consistently during online gameplay. Looking at open connections with TCPView and seeing hundreds of sequential ports being opened for listening for a brief period of time and closing. SSH-Agent is started with Github for windows, but for some odd reason does not exit with the program. It seems to cause network issues, especially with windows becoming overly busy with port delegation.

**Comment by dscho** [comment]
Given that `git grep -I ssh-agent` suggests that the `ssh-agent` is started only when you run `cmd/start-ssh-agent.cmd`.

I suspect that you did not quite manage to direct this ticket to the correct place: you found the issue tracker for the development environment for *Git for Windows*. I.e. not Git*Hub* for Windows.

BTW the reason the `ssh-agent` does not quit when GitHub for Windows quits is easily explained: this is expected behavior! The agent *should* keep running so that you do not have to type in your passphrase all the time. The only problem is that the agent is started *again* when it already runs; that is the bug. But as I pointed out: not in Git for Windows.

Maybe @shiftkey is able to direct you to the correct place to report this issue?

**Comment by shiftkey** [comment]
@PING can you drop an email to support@github.com with details (can TCPView export logs? it's been many years since I've used it) so I can look into this?

I don't believe we're doing anything exceptional with ssh-agent.exe, but I'd still like to get to the bottom of it.
