### ISSUE TITLE
Is there any way to get password prompt directly in console rather than via popup?

### ISSUE THREAD

**Issue by kalanbates** [msysgit/msysgit#325]
Just changed my msysgit version today from [1.9.4-preview20140815] to [2.7.0] and noticed that when I attempt to contact a secure site, I am no longer prompted for my password directly within the console, but via a popup.  

Is there anything I can do to switch this behavior back to requesting my password the way it used to be?
thanks.

**Comment by dscho** [comment]
You almost certainly did not switch msysgit to 2.7.0.

And yes, you can disable that behavior by deleting the following lines in `/etc/profile.d/env.sh`:

```sh
# Allow SSH to ask via GUI if the terminal is not usable
test -n "$SSH_ASKPASS" || {
        case "$MSYSTEM" in
        MINGW64)
                export DISPLAY=needs-to-be-defined
                export SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
                ;;
        MINGW32)
                export DISPLAY=needs-to-be-defined
                export SSH_ASKPASS=/mingw32/libexec/git-core/git-gui--askpass
                ;;
        esac
}
```

Please note also that this bug tracker is
1. obsolete because msysgit is obsolete
2. intended for bugs, not for requests for help (the mailing list is the appropriate forum)
